name: shopease_admin
description: "ShopEase - E-commerce Admin Panel"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.10.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  intl: any  # Add this line
  provider:
  shared_preferences:
  fl_chart:
  cupertino_icons: ^1.0.8
  http:   # API calls ke liye
  shimmer:   # Loading effects
  animations:   # Smooth animations
  flutter_markdown:   # Markdown support


flutter:
  uses-material-design: true

  # Add this section for localization
  generate: true

  assets:
    - assets/images/